WITH
{{ build_fivetran_ctes_from_one_schema_table(
    schema_base_name = 'STRIPE', 
    table_name = 'PAYMENT_INTENT', 
    columns = ['ID',	'CONNECTED_ACCOUNT_ID',	'PAYMENT_METHOD_TYPES',	'AMOUNT',	'AMOUNT_CAPTURABLE',	'AMOUNT_RECEIVED',	'APPLICATION',	'APPLICATION_FEE_AMOUNT',	'CANCELED_AT',	'CANCELLATION_REASON',	'CAPTURE_METHOD',	'CONFIRMATION_METHOD',	'CREATED',	'CURRENCY',	'DESCRIPTION',	'LAST_PAYMENT_ERROR_TYPE',	'LAST_PAYMENT_ERROR_CODE',	'LAST_PAYMENT_ERROR_DECLINE_CODE',	'LAST_PAYMENT_ERROR_DOC_URL',	'LAST_PAYMENT_ERROR_MESSAGE',	'LAST_PAYMENT_ERROR_PARAM',	'LAST_PAYMENT_ERROR_SOURCE_ID',	'LAST_PAYMENT_ERROR_CHARGE_ID',	'LIVEMODE',	'METADATA',	'ON_BEHALF_OF',	'RECEIPT_EMAIL',	'STATEMENT_DESCRIPTOR',	'STATUS',	'TRANSFER_DATA_DESTINATION',	'TRANSFER_GROUP',	'PAYMENT_METHOD_ID',	'CUSTOMER_ID',	'SOURCE_ID',	'_FIVETRAN_SYNCED'],
    cte_prefix='base') }}

SELECT 
BASE_UNION.ERAD_CUSTOMER_ID,
'UTC' as TIMEZONE_NAME, -- TODO timezone is static because there isnt a column currently providing the field
{{ convert_to_erad_tz('BASE_UNION.CREATED::date', 'TIMEZONE_NAME') }} as ERAD_TIMESTAMP,
1 as transactions,
BASE_UNION.ID,
BASE_UNION.CONNECTED_ACCOUNT_ID,
BASE_UNION.PAYMENT_METHOD_TYPES,
BASE_UNION.AMOUNT,
BASE_UNION.AMOUNT_CAPTURABLE,
BASE_UNION.AMOUNT_RECEIVED,
BASE_UNION.APPLICATION,
BASE_UNION.APPLICATION_FEE_AMOUNT,
BASE_UNION.CANCELED_AT,
BASE_UNION.CANCELLATION_REASON,
BASE_UNION.CAPTURE_METHOD,
BASE_UNION.CONFIRMATION_METHOD,
BASE_UNION.CREATED,
BASE_UNION.CURRENCY,
BASE_UNION.DESCRIPTION,
BASE_UNION.LAST_PAYMENT_ERROR_TYPE,
BASE_UNION.LAST_PAYMENT_ERROR_CODE,
BASE_UNION.LAST_PAYMENT_ERROR_DECLINE_CODE,
BASE_UNION.LAST_PAYMENT_ERROR_DOC_URL,
BASE_UNION.LAST_PAYMENT_ERROR_MESSAGE,
BASE_UNION.LAST_PAYMENT_ERROR_PARAM,
BASE_UNION.LAST_PAYMENT_ERROR_SOURCE_ID,
BASE_UNION.LAST_PAYMENT_ERROR_CHARGE_ID,
BASE_UNION.LIVEMODE,
BASE_UNION.METADATA,
BASE_UNION.ON_BEHALF_OF,
BASE_UNION.RECEIPT_EMAIL,
BASE_UNION.STATEMENT_DESCRIPTOR,
BASE_UNION.STATUS,
BASE_UNION.TRANSFER_DATA_DESTINATION,
BASE_UNION.TRANSFER_GROUP,
BASE_UNION.PAYMENT_METHOD_ID,
BASE_UNION.CUSTOMER_ID,
BASE_UNION.SOURCE_ID,
BASE_UNION._FIVETRAN_SYNCED,
{{ convert_to_erad_currency('BASE_UNION.CURRENCY' ,'(BASE_UNION.AMOUNT/100)') }} as ERAD_REVENUE,
BASE_UNION.ERAD_SCHEMA,
BASE_UNION.ERAD_TABLE

FROM BASE_UNION
WHERE status = 'succeeded'